### ISSUE TITLE
How to set top margin for FullScreenDialog ?

### ISSUE THREAD

**Issue by broscr** [kongzue/DialogX#188]
I tried this but not work.
```
RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
layoutParams.setMargins(0,20,0,0);
dialog.getDialogImpl().boxCustom.getRootView().setLayoutParams(layoutParams);
```

**Comment by kongzue** [comment]
It is not directly set up.
The height of FullScreenDialog is based on the content layout height, you can try to modify the content layout to set an exact value of the height.
For example, the custom content layout used by FullScreenDialog in the demo project: 
https://github.com/kongzue/DialogX/blob/master/app/src/main/res/layout/layout_full_login.xml
Or you can use the exact height in your root layout.

Another way is to get DialogImpl object, which is a concrete instance of a dialog box, and you can manipulate any basic component of the dialog box by getting it.
Please note that you must get the dialog after it is instantiated, otherwise a NullPointerException will occur.
Examples.
```
FullScreenDialog.show(new OnBindView<FullScreenDialog>(R.layout.layout_full_webview) {
    @Override
    public void onBind(final FullScreenDialog dialog, View v) {
        RelativeLayout.LayoutParams rLp = (RelativeLayout.LayoutParams) dialog.getDialogImpl().bkg.getLayoutParams();
        if (rLp == null) {
            rLp = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        }
        rLp.topMargin = dip2px(100);
        dialog.getDialogImpl().bkg.setLayoutParams(rLp);

        //ToDo...
    }
});
```

**Comment by broscr** [comment]
Ohh that is right. Thanks
