### ISSUE TITLE
【BUG反馈】空指针异常

### ISSUE THREAD

**Issue by hebing521** [kongzue/DialogX#203]
## BUG 反馈

请先确认您已阅读[《常见问题》](https://github.com/kongzue/DialogX/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

### 问题描述：
WaitDialog.show("")方法调用后出现异常
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.init(WaitDialog.java:312)
        at com.kongzue.dialogx.dialogs.WaitDialog$DialogImpl.lazyCreate(WaitDialog.java:277)
        at com.kongzue.dialogx.dialogs.WaitDialog$1.run(WaitDialog.java:211)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

### 设备信息：
三星 SM-T380C
android 8.1.0

### 是否在 Demo 中能复现此问题？
否

### 问题截图/视频
请在此插入佐证问题的截图和视频。

**Comment by kongzue** [comment]
请问是使用最新版本么？未能在 [WaitDialog.java:312](https://github.com/kongzue/DialogX/blob/ee5748de6db84d57cb526c0ac448fbeb9881ce5a/DialogX/src/main/java/com/kongzue/dialogx/dialogs/WaitDialog.java#L312) 找到 `.get()` 相关代码。

**Comment by ALuoBo** [comment]
复现
dialogx_version = "0.0.45.beta17"

请问，dialog直接在声明时构造是否会出现问题？

问题代码：
`class SearchFragment : DataBindingFragment() {
     xxxx
    private val dateDialog: CustomDialog =
        CustomDialog.build()
            .setCustomView(object :OnBindView<CustomDialog>(R.layout.dialog_calendar){
                override fun onBind(dialog: CustomDialog?, v: View?) {

                }

            })

    override fun onResume() {
        super.onResume()
        dateDialog.show() // 调用即出现 空指针异常
    }
}`

**Comment by kongzue** [comment]
不影响，但是show的时候建议用带参数的.show(activity)，自动获取context可能有延迟不能在activity创建时拿得到
________________________________
发件人: ALuoBo ***@***.***>
发送时间: Monday, June 13, 2022 1:34:55 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203)


复现
dialogx_version = "0.0.45.beta17"

请问，dialog直接在声明时构造是否会出现问题？

问题代码：
`class SearchFragment : DataBindingFragment() {
xxxx
private val dateDialog: CustomDialog =
CustomDialog.build()
.setCustomView(object :OnBindView(R.layout.dialog_calendar){
override fun onBind(dialog: CustomDialog?, v: View?) {

            }



        })



override fun onResume() {

    super.onResume()

    dateDialog.show() // 调用即出现 空指针异常

}



}`

―

**Comment by ALuoBo** [comment]
> 不影响，但是show的时候建议用带参数的.show(activity)，自动获取context可能有延迟不能在activity创建时拿得到
> […](#)
> ________________________________ 发件人: ALuoBo ***@***.***> 发送时间: Monday, June 13, 2022 1:34:55 PM 收件人: kongzue/DialogX ***@***.***> 抄送: Kongzue ***@***.***>; Comment ***@***.***> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203) 复现 dialogx_version = "0.0.45.beta17" 请问，dialog直接在声明时构造是否会出现问题？ 问题代码： `class SearchFragment : DataBindingFragment() { xxxx private val dateDialog: CustomDialog = CustomDialog.build() .setCustomView(object :OnBindView(R.layout.dialog_calendar){ override fun onBind(dialog: CustomDialog?, v: View?) { } }) override fun onResume() { super.onResume() dateDialog.show() // 调用即出现 空指针异常 } }` ― Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9yiliu5wbcplaFH0I7muwkNvaTlc7EUutuS71KWFSQA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xz3NXJFP9xyUWJ37YZl6zTCJ9A1FjQ5VOx2RsqegA1E%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>

传入 activity 之后，不再报空 , 意外发现，dialogx 报  **DialogX.init: 初始化异常，context 为 null 或未初始化**

**Comment by kongzue** [comment]
请排查Android Manifest中是否关联Application类以及Application#onCreate是否顺利执行DialogX#init初始化方法
________________________________
发件人: ALuoBo ***@***.***>
发送时间: Monday, June 13, 2022 1:47:48 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203)


不影响，但是show的时候建议用带参数的.show(activity)，自动获取context可能有延迟不能在activity创建时拿得到
…
________________________________ 发件人: ALuoBo @.> 发送时间: Monday, June 13, 2022 1:34:55 PM 收件人: kongzue/DialogX @.> 抄送: Kongzue @.>; Comment @.> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uR0Ae7N0NBfV%2BDYmaRIS1%2Fre8Xkx9HDY3ytkmoQlyWk%3D&reserved=0>) 复现 dialogx_version = "0.0.45.beta17" 请问，dialog直接在声明时构造是否会出现问题？ 问题代码： class SearchFragment : DataBindingFragment() { xxxx private val dateDialog: CustomDialog = CustomDialog.build() .setCustomView(object :OnBindView(R.layout.dialog_calendar){ override fun onBind(dialog: CustomDialog?, v: View?) { } }) override fun onResume() { super.onResume() dateDialog.show() // 调用即出现 空指针异常 } } D Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9yiliu5wbcplaFH0I7muwkNvaTlc7EUutuS71KWFSQA%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ddpxGFHLkvEGqQE0aWfmRWbA9zVpo9QpDOpVqgjGvWk%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xz3NXJFP9xyUWJ37YZl6zTCJ9A1FjQ5VOx2RsqegA1E%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z5zK7%2FS4t%2BLFtKY5PccIlUi9IaQ6q90Kol75q4X6VFg%3D&reserved=0>. You are receiving this because you commented.Message ID: @.***>

传入 activity 之后，不再报空 , 意外发现，dialogx 报 DialogX.init: 初始化异常，context 为 null 或未初始化

―

**Comment by ALuoBo** [comment]
> 请排查Android Manifest中是否关联Application类以及Application#onCreate是否顺利执行DialogX#init初始化方法
> […](#)
> ________________________________ 发件人: ALuoBo ***@***.***> 发送时间: Monday, June 13, 2022 1:47:48 PM 收件人: kongzue/DialogX ***@***.***> 抄送: Kongzue ***@***.***>; Comment ***@***.***> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203) 不影响，但是show的时候建议用带参数的.show(activity)，自动获取context可能有延迟不能在activity创建时拿得到 …
> ________________________________ 发件人: ALuoBo @.> 发送时间: Monday, June 13, 2022 1:34:55 PM 收件人: kongzue/DialogX @.> 抄送: Kongzue @.>; Comment @.> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uR0Ae7N0NBfV%2BDYmaRIS1%2Fre8Xkx9HDY3ytkmoQlyWk%3D&reserved=0>) 复现 dialogx_version = "0.0.45.beta17" 请问，dialog直接在声明时构造是否会出现问题？ 问题代码： class SearchFragment : DataBindingFragment() { xxxx private val dateDialog: CustomDialog = CustomDialog.build() .setCustomView(object :OnBindView(R.layout.dialog_calendar){ override fun onBind(dialog: CustomDialog?, v: View?) { } }) override fun onResume() { super.onResume() dateDialog.show() // 调用即出现 空指针异常 } } D Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9yiliu5wbcplaFH0I7muwkNvaTlc7EUutuS71KWFSQA%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ddpxGFHLkvEGqQE0aWfmRWbA9zVpo9QpDOpVqgjGvWk%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xz3NXJFP9xyUWJ37YZl6zTCJ9A1FjQ5VOx2RsqegA1E%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z5zK7%2FS4t%2BLFtKY5PccIlUi9IaQ6q90Kol75q4X6VFg%3D&reserved=0>. You are receiving this because you commented.Message ID: @.***> 传入 activity 之后，不再报空 , 意外发现，dialogx 报 DialogX.init: 初始化异常，context 为 null 或未初始化 ― Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153498441&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OFOqzJHJkHuC6bgrpOv%2FQd5h9jq5GEQbbN7z2PithsE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH7SYOQIUOMO4V4TRKLVO3DQJANCNFSM5YBFITZA&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9GD0BJN3%2BelR8P%2BQL2TiPPG6WX600FoOVgSc%2FvKAJzw%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>

多谢，，我的问题是由于使用错误， 未在 Application init dialogx ,  已删除之前的描述，以免干扰原 issue

**Comment by kongzue** [comment]
不客气，如有疑问也可加群反馈
________________________________
发件人: ALuoBo ***@***.***>
发送时间: Monday, June 13, 2022 1:56:24 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203)


请排查Android Manifest中是否关联Application类以及Application#onCreate是否顺利执行DialogX#init初始化方法
…
________________________________ 发件人: ALuoBo @.> 发送时间: Monday, June 13, 2022 1:47:48 PM 收件人: kongzue/DialogX @.> 抄送: Kongzue @.>; Comment @.> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DHPNTRUwtNox6UaAoYoAfOxOd%2BKKVp2sGuPCgd22zyE%3D&reserved=0>) 不影响，但是show的时候建议用带参数的.show(activity)，自动获取context可能有延迟不能在activity创建时拿得到 …
________________________________ 发件人: ALuoBo @.> 发送时间: Monday, June 13, 2022 1:34:55 PM 收件人: kongzue/DialogX @.> 抄送: Kongzue @.>; Comment @.> 主题: Re: [kongzue/DialogX] 【BUG反馈】空指针异常 (Issue #203<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DHPNTRUwtNox6UaAoYoAfOxOd%2BKKVp2sGuPCgd22zyE%3D&reserved=0>https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uR0Ae7N0NBfV%2BDYmaRIS1%2Fre8Xkx9HDY3ytkmoQlyWk%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DHPNTRUwtNox6UaAoYoAfOxOd%2BKKVp2sGuPCgd22zyE%3D&reserved=0>) 复现 dialogx_version = "0.0.45.beta17" 请问，dialog直接在声明时构造是否会出现问题？ 问题代码： class SearchFragment : DataBindingFragment() { xxxx private val dateDialog: CustomDialog = CustomDialog.build() .setCustomView(object :OnBindView(R.layout.dialog_calendar){ override fun onBind(dialog: CustomDialog?, v: View?) { } }) override fun onResume() { super.onResume() dateDialog.show() // 调用即出现 空指针异常 } } D Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9yiliu5wbcplaFH0I7muwkNvaTlc7EUutuS71KWFSQA%3D&reserved=0https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ddpxGFHLkvEGqQE0aWfmRWbA9zVpo9QpDOpVqgjGvWk%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153491664&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=71DLYUZDbDpFnA7lllYtZp2p29oy9ScZ%2FoxXAKmtREE%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7C5f7c760df7344035b89508da4cfe7331%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906953007183181%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xz3NXJFP9xyUWJ37YZl6zTCJ9A1FjQ5VOx2RsqegA1E%3D&reserved=0https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z5zK7%2FS4t%2BLFtKY5PccIlUi9IaQ6q90Kol75q4X6VFg%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH22MOH5QEZHH4CSLLTVO3B77ANCNFSM5YBFITZA&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LuFjmYG1tVH18M3JeoIO0DDL67LGISY5DC0IN42GdHw%3D&reserved=0>. You are receiving this because you commented.Message ID: @.> 传入 activity 之后，不再报空 , 意外发现，dialogx 报 DialogX.init: 初始化异常，context 为 null 或未初始化 D Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153498441&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OFOqzJHJkHuC6bgrpOv%2FQd5h9jq5GEQbbN7z2PithsE%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F203%23issuecomment-1153498441&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GjctdE%2FzmirInUvkGEoy%2FlI0X8FJoHZh9qMa05f8f74%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH7SYOQIUOMO4V4TRKLVO3DQJANCNFSM5YBFITZA&data=05%7C01%7C%7Cd40378e31bb241bc23d208da4d003f9b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906960708951617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9GD0BJN3%2BelR8P%2BQL2TiPPG6WX600FoOVgSc%2FvKAJzw%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH7SYOQIUOMO4V4TRKLVO3DQJANCNFSM5YBFITZA&data=05%7C01%7C%7Cdab7447421854d0480bb08da4d01733d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906965894374976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M%2BDlHHtUeHPl2kGuJOpc%2BkLpElsKP3tYRCU%2FFmH47Sw%3D&reserved=0>. You are receiving this because you commented.Message ID: @.>

多谢，，我的问题是由于使用错误， 未在 Application init dialogx , 已删除之前的描述，以免干扰原 issue

―
