### ISSUE TITLE
【功能建议】不知道有没有想法使用databinding+livedata实现无闪屏、不重启dialog 实时换肤

### ISSUE THREAD

**Issue by Matchas-xiaobin** [kongzue/DialogX#211]
## 功能建议
希望大佬能写个databinding版本，实现无闪屏换肤。

### 需求描述：
虽然目前的版本，可以通过调用DialogX.globalTheme = DialogX.THEME.DARK的方式做到下一次弹出时换肤，但是在activity不recreate的情况下，不能自动换肤。
所以，希望大佬能写个databinding版本，使用DataBinding绑定布局，然后设置activity或者fragment的lifecycleOwner，实现LiveData自动换肤。
参考：[Databinding+LiveData轻松实现无重启换肤](https://github.com/czy1121/ThemeDemo)

**Comment by kongzue** [comment]
当前 DialogX 默认是支持自动按照亮暗色进行切换的，
请使用设置：
```
DialogX.globalTheme = DialogX.THEME.AUTO;
```
在 Google Pixel5(Android 13 beta2)下测试通过：
![image](https://user-images.githubusercontent.com/10115359/176812601-decfcf87-a36c-446b-89b2-ae812610d088.png)

**Comment by Matchas-xiaobin** [comment]
> 当前 DialogX 默认是支持自动按照亮暗色进行切换的，
> 请使用设置：
> ```
> DialogX.globalTheme = DialogX.THEME.AUTO;
> ```
> 在 Google Pixel5(Android 13 beta2)下测试通过：
> ![image](https://user-images.githubusercontent.com/10115359/176812601-decfcf87-a36c-446b-89b2-ae812610d088.png)
> 

我想，你大概没明白我的意思。
我没有让系统接管app的主题变更，也就是说，系统切到深色模式，app不会自动处理，也就是不会走recreate。
简单来讲，就是我拦截了系统切换到深色模式，然后自己手动把界面上的控件改了颜色，没有走重建activity界面。

**Comment by kongzue** [comment]
那么你需要手动调用对话框的restart方法，DialogX的对话框构建中主题不是通过XML style配置的，有很多需要重新加载，只能使用restart重新启动对话框。
________________________________
发件人: xiaobin ***@***.***>
发送时间: Friday, July 1, 2022 12:41:37 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【功能建议】不知道有没有想法使用databinding+livedata实现无闪屏、不重启dialog 实时换肤 (Issue #211)


当前 DialogX 默认是支持自动按照亮暗色进行切换的，
请使用设置：

DialogX.globalTheme = DialogX.THEME.AUTO;


在 Google Pixel5(Android 13 beta2)下测试通过：
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10115359%2F176812601-decfcf87-a36c-446b-89b2-ae812610d088.png&data=05%7C01%7C%7C5f89ab91bb164459872808da5b1bfc8b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922473035317561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NnyoflPzYnxJgneu0C%2BRWZMq4NZ6lUxL6WOfejKEU5g%3D&reserved=0>

我想，你大概没明白我的意思。
我没有让系统接管app的主题变更，也就是说，系统切到深色模式，app不会自动处理，也就是不会走recreate。
简单来讲，就是我拦截了系统切换到深色模式，然后自己手动把界面上的控件改了颜色，没有走重建activity界面。

―

**Comment by kongzue** [comment]
做不到，涉及的元素过多，不仅仅是颜色需要调整，很多组件的资源都需要根据主题重新加载，直接进行UI刷新目前做不到，除非修改整个结构逻辑并放弃部分主题支持。
________________________________
发件人: xiaobin ***@***.***>
发送时间: 2022年7月1日 8:15
收件人: kongzue/DialogX ***@***.***>
抄送: Kongzue ***@***.***>; Comment ***@***.***>
主题: Re: [kongzue/DialogX] 【功能建议】不知道有没有想法使用databinding+livedata实现无闪屏、不重启dialog 实时换肤 (Issue #211)


那么你需要手动调用对话框的restart方法，DialogX的对话框构建中主题不是通过XML style配置的，有很多需要重新加载，只能使用restart重新启动对话框。
…
________________________________ 发件人: xiaobin @.> 发送时间: Friday, July 1, 2022 12:41:37 PM 收件人: kongzue/DialogX @.> 抄送: Kongzue @.>; Comment @.> 主题: Re: [kongzue/DialogX] 【功能建议】不知道有没有想法使用databinding+livedata实现无闪屏、不重启dialog 实时换肤 (Issue #211<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F211&data=05%7C01%7C%7C0930a536fc79447dd7e908da5b39e5cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922601490284626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0uBMwSi1KoEEYIYUvO8S5nsYdMtpG0VH1CGjtl49jQE%3D&reserved=0>) 当前 DialogX 默认是支持自动按照亮暗色进行切换的， 请使用设置： DialogX.globalTheme = DialogX.THEME.AUTO; 在 Google Pixel5(Android 13 beta2)下测试通过： [image]https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10115359%2F176812601-decfcf87-a36c-446b-89b2-ae812610d088.png&data=05%7C01%7C%7C5f89ab91bb164459872808da5b1bfc8b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922473035317561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NnyoflPzYnxJgneu0C%2BRWZMq4NZ6lUxL6WOfejKEU5g%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F10115359%2F176812601-decfcf87-a36c-446b-89b2-ae812610d088.png&data=05%7C01%7C%7C0930a536fc79447dd7e908da5b39e5cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922601490284626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LShTeE5RET2ekeCMnqVwv8bq3xi6dq1EtHrXnbKQJR8%3D&reserved=0> 我想，你大概没明白我的意思。 我没有让系统接管app的主题变更，也就是说，系统切到深色模式，app不会自动处理，也就是不会走recreate。 简单来讲，就是我拦截了系统切换到深色模式，然后自己手动把界面上的控件改了颜色，没有走重建activity界面。 D Reply to this email directly, view it on GitHubhttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F211%23issuecomment-1171928297&data=05%7C01%7C%7C5f89ab91bb164459872808da5b1bfc8b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922473035317561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DuCiGyZeP0OoBxHisTZ313gMO67LnzdNJstmCMNbLRU%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkongzue%2FDialogX%2Fissues%2F211%23issuecomment-1171928297&data=05%7C01%7C%7C0930a536fc79447dd7e908da5b39e5cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922601490284626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7noWOqbp4ESwNo94jgwOYfl1cB6jl2pbjfpwwJhBIpM%3D&reserved=0>, or unsubscribehttps://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH6NG5LOM62HJ4TCNV3VRZZIDANCNFSM52HZ7KJQ&data=05%7C01%7C%7C5f89ab91bb164459872808da5b1bfc8b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922473035317561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0Qtor9yo9wpiYzgKHClD6GnBzNUvJjJirqaYpbMj3Q8%3D&reserved=0<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFSH6NG5LOM62HJ4TCNV3VRZZIDANCNFSM52HZ7KJQ&data=05%7C01%7C%7C0930a536fc79447dd7e908da5b39e5cd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637922601490284626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ESLSz6%2B0AjvyAtIcJvoBIL39Vjj2sarH8KdLcYQbLZ8%3D&reserved=0>. You are receiving this because you commented.Message ID: @.***>

那能不能提供一个方法，调用后直接重新加载界面布局，但是不去重启dialog呢，重启体验不好。

―

**Comment by Matchas-xiaobin** [comment]
> 

好吧，感谢大佬抽空为我解答。
