### ISSUE TITLE
【BUG反馈】 深色模式下，CookieBar 会闪退

### ISSUE THREAD

**Issue by chejfj** [kongzue/DialogX#389]
### 问题描述

参照了例子的代码，写了一个双击退出的方法，代码如下：`  CookieBar.builder(MainActivity.this)
                    .setTitle("再按一次退出")
                    .setMessage("再按一次退出魔盒，响应时间间隔为1.5S，在这段事件再此点击返回键即可退出")
                    .setDuration(3000)
                    .setBackgroundColor(R.color.浅蓝色)
                    .setActionColor(android.R.color.white)
                    .setTitleColor(android.R.color.white)
                    .show();`，在浅色模式下是正常的可以从顶部弹出提示，但是深色模式下就会闪退，报错信息为：` Caused by: android.view.InflateException: Binary XML file line #17 in com.hydrogen.newxmh:layout/xui_layout_cookie: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException`，看样子好像是布局文件和反射机制出了问题。一时间不知道如何解决。

### DialogX 版本

1.2.1

### 设备信息

小米10Ultra

### 是否在 Demo 中能复现此问题？

否

### 问题截图/视频

截屏/视频

### 错误日志

```java
Caused by: android.view.InflateException: Binary XML file line #17 in com.hydrogen.newxmh:layout/xui_layout_cookie: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
```

**Comment by kongzue** [comment]
请确认您的问题跟DialogX相关
________________________________
发件人: Zhuzngzhou ***@***.***>
发送时间: Thursday, October 19, 2023 7:32:42 PM
收件人: kongzue/DialogX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kongzue/DialogX] 【BUG反馈】 深色模式下，CookieBar 会闪退 (Issue #389)


问题描述

参照了例子的代码，写了一个双击退出的方法，代码如下： CookieBar.builder(MainActivity.this) .setTitle("再按一次退出") .setMessage("再按一次退出魔盒，响应时间间隔为1.5S，在这段事件再此点击返回键即可退出") .setDuration(3000) .setBackgroundColor(R.color.浅蓝色) .setActionColor(android.R.color.white) .setTitleColor(android.R.color.white) .show();，在浅色模式下是正常的可以从顶部弹出提示，但是深色模式下就会闪退，报错信息为： Caused by: android.view.InflateException: Binary XML file line #17 in com.hydrogen.newxmh:layout/xui_layout_cookie: Error inflating class <unknown> Caused by: java.lang.reflect.InvocationTargetException，看样子好像是布局文件和反射机制出了问题。一时间不知道如何解决。

DialogX 版本

1.2.1

设备信息

小米10Ultra

是否在 Demo 中能复现此问题？

否

问题截图/视频

截屏/视频

错误日志

Caused by: android.view.InflateException: Binary XML file line #17 in com.hydrogen.newxmh:layout/xui_layout_cookie: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException

―

**Comment by chejfj** [comment]
乖乖，XUI的问题弄到DialogX去了，哈哈迷糊了
